# Generated by Django 2.2.2 on 2019-06-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('bauthor', models.CharField(max_length=150)),
                ('bquan', models.CharField(max_length=500)),
            ],
        ),
    ]
